---
title: "SMO-Bad Publicity"
author: "Sophie Hensgen"
date: "6/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packagest, include=FALSE}
library(foreign)
library(dplyr)
library(ggplot2)
library(tidyr)
library(anytime)
library(writexl)
library(readxl)
library(MASS)
```

```{r data set, echo=FALSE}
prodat <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Protets/prodat_1950-2002_OG.dta")
prodat
```


```{r Creation of new Variable, include=FALSE}
#Variables I will use to find out which protest belong together

#- PEN --> Protestereignisnummer
#- NCLAIM1--> Themenfeld 
#- BEWEG --> Bewegung
#- BEWEG1 & BEWEG2 --> Welche Bewegung
#- OBJEKT1 & OBJEKT2 --> Gegen wen richtet es sich?
#- JAHRN --> Jahr
#- MONATN --> Monat
#- TAGN --> Tag
#- ETAG --> Ereignistag (Wochentag)
#- TINI --> Initiativen, Gruppen und Netzwerke 
#- TINITX1 & TINITX2 --> Name 
#- TINICO1 & TINICO2 --> Codenummer
#- TINIFU1 & TINIFU2 --> Veranstalter
#- TVERB --> Gewerkschaften, Verbände, Kirchen
#- TVERB1 & TVERB2 --> Name
#- TVERBCO1 & TVERBCO2 --> Codenummer
#- KAM --> Ist PE Teil einer Kampagne?
#- KAMCO --> Kampagnennummer
```

```{r dependent variable, include=FALSE}
#Dependent Variable: 
#- New Variable which says which protests belongs together
#- ZAHL --> Anzahl der Teilnehmer
```
```{r independent variables, echo=FALSE}
#Independent Variables:

#Evaluation interest group
#- VSTATE --> Statements von Interessengruppen
#- VSTABE1 & VSTABE2 --> Bewertung
```

```{r independent variables, echo=FALSE}
#Independent Variables:

#Evaluation political side
#- SSTATE --> Statements von politischadministrativer Seite
#- STATBE1 & STATBE2 --> Bewertung
```

```{r controll variables - Injuries, include=FALSE}
#Injured during the Protest
#- VERLETZT --> Verletzte?

```

```{r control variable - Deaths, include=FALSE}
#Death during the Protest
#- TOTE --> Tote im generellen
```

```{r control variables - Gegenproteste, include=FALSE}
#Gegenproteste:
#- AUSJA --> Gegenproteste
#- AUSPEN --> Gegen wen Gegenproteste
#- GEGJA --> Ist PE ein Gegenprotest?
#- GEGENPEN --> Gegen wen?
```

```{r control variables - News Coverage, include=FALSE}
#News Coverage
#- ARTZAHL --> Artikelanzahl
```

```{r control variables - Day of week, include=FALSE}
#Day of Protest
#- ETAG --> Ereignistag (Wochentag)
```

```{r control variables - Activity, include=FALSE}
#Aktionsform
#- FORM1 & FORM21 --> Aktionsform
```

```{r control variables - Property damage, include=FALSE}
#Sachbeschädigung
#- SCHADEN --> Sachbeschädigung
```

```{r control variables - Arrests, include=FALSE}
#Festnahmen
#- FESTNAHM --> Wie viele Festnehmen
```

```{r control variables - Area, include=FALSE}
#Area
#- ORT1 & ORT2c --> Hauptorte
#- BRD1 & BRD2 --> West/Ost
```

```{r data set, echo=FALSE}
#new data set with all the important variables

pro <-  dplyr::select(prodat, pen, nclaim1, nclaim2, jahrn, monatn, tagn, etag, tini, tinitx1, tinitx2, tinico1, tinico2, tinifu1, tinifu2, tverb, tverb1, tverb2, tverbco1, tverbco2, tverbfu1, tverbfu2, kam, kamco, tallzahl, nclaim1, nclaim2, vstate, vstabe1, vstabe2, sstate, statbe1, statbe2, verletzt, tote, artzahl, etag, form1, form2, schaden, festnahm, ort1, ort2, brd1, brd2, zahl, formtx)

p <- dplyr::select(pro, jahrn, monatn, tagn, etag, tinico1, tinico2, tinifu1, tinifu2, tverbco1, tverbco2, tverbfu1, tverbfu2, tallzahl, vstate, vstabe1, vstabe2, sstate, statbe1, statbe2, verletzt, artzahl, etag, form1, form2, schaden, festnahm, zahl, formtx, ort1)

p$etag <- as.character(p$etag)
p$tinifu1 <- as.character(p$tinifu1)
p$tinifu2 <- as.character(p$tinifu2)
p$tverbfu1 <- as.character(p$tverbfu1)
p$tverbfu2 <- as.character(p$tverbfu2)
#p$verletzt <- as.character(p$verletzt)
p$form2 <- as.character(p$form2)
#p$schaden <- as.character(p$schaden)
#p$festnahm <- as.character(p$festnahm)

p$sstate <- as.integer(p$sstate)
p$vstate <- as.integer(p$vstate)
p$festnahm <- as.integer(p$festnahm)
p$schaden <- as.integer(p$schaden)
p$verletzt <- as.integer(p$verletzt)

p[p==""]<-NA
p$sstate <- as.integer(p$sstate)
p$vstate <- as.integer(p$vstate)
p <- p %>% replace_na(list(tverbco1 = "not", tverbco2 = "not", tinico1 = "not", tinico2 = "not", statbe1 = "not", statbe2 = "not", vstabe2 = "not", vstabe1 = "not", sstate = "not", vstate = "not", zahl = "not", verletzt = "not", artzahl = "not", etag = "not", festnahm = "not", schaden = "not", form1 = "not", form2 = "not", formtx = "not", ort1 = "not"))
p


p <- p %>% mutate(i_bewert = coalesce(vstate, sstate)) %>%
           mutate(i_codeverb = coalesce(tverbco1, tverbco2)) %>%
           mutate(i_codeini = coalesce(tinico1, tinico2)) %>%
           mutate(i_bewertint = coalesce(vstabe1, vstabe2)) %>%
           mutate(i_bewertpol = coalesce(statbe1, statbe2)) %>%
           mutate(form = coalesce(form1, form2)) %>%
         dplyr::select(i_bewert, i_codeini, i_codeverb, i_bewertint, i_bewertpol, zahl, verletzt, artzahl, etag, festnahm, schaden, form, formtx, jahrn, monatn, tagn, ort1)



p[p=="not"]<-NA
p
p$i_codeini <- as.integer(p$i_codeini)
p$i_codeverb <- as.integer(p$i_codeverb)
p$i_bewertint <- as.integer(p$i_bewertint)
p$i_bewertpol <- as.integer(p$i_bewertpol)
p$zahl <- as.integer(p$zahl)
p$artzahl <- as.integer(p$artzahl)
p$form<- as.integer(p$form)
p <- p %>% replace_na(list(i_codeini = "not", i_codeverb = "not", i_bewertint = "not", i_bewertpol = "not", verletzt = "not", artzahl = "not", etag = "not", festnahm = "not", schaden = "not", form = "not", formtx = "not", ort1 = "not"))
p <- na.omit(p, cols=="i_bewert")
p <- na.omit(p, cols=="zahl")

p[p=="not"]<-NA
p
```

```{r data set, echo=FALSE}

# create a date variable
p <- unite(p, date, tagn, monatn, jahrn, sep = "-")

p$date <-  format(as.Date(p$date, "%d-%m-%y"), "19%y-%m-%d")


p$date <- gsub("1902", "2002", p$date)
p$date <- gsub("1901", "2001", p$date)
p$date <- gsub("1900", "2000", p$date)

p$date <- as.Date(p$date, "%Y-%m-%d")
```

```{r data set, echo=FALSE}
# Correct the order of the variables

p <-  arrange(p, date)

p <- p[, c("i_bewert", "date", "i_codeini", "i_codeverb", "ort1", "i_bewertint", "i_bewertpol", "zahl", "artzahl", "verletzt", "schaden", "festnahm", "form", "formtx", "etag")] 

p <-  arrange(p, i_codeverb)


```

```{r var aufbereitung - Area, echo=FALSE}

# wenn verletzt 1, wenn nicht 0
p$verletzt <- gsub("1", "0", p$verletzt, fixed = TRUE)
p$verletzt <- gsub("2", "1", p$verletzt, fixed = TRUE)
p$verletzt <- gsub("3", NA, p$verletzt , fixed = TRUE)

# wenn festnahme geschehen 1, wenn nicht 0
p$festnahm <- gsub("2", "0", p$festnahm, fixed = TRUE)
p$festnahm <- gsub("3", NA, p$festnahm, fixed = TRUE)

# wenn Sachschaden geschehen 1, wenn nicht 0
p$schaden <- gsub("2", "0", p$schaden, fixed = TRUE)
p$schaden  <- gsub("3", NA, p$schaden, fixed = TRUE)

# Wochentage von 1-7
p$etag <- gsub("montag", "1", p$etag, fixed = TRUE)
p$etag <- gsub("dienstag", "2", p$etag, fixed = TRUE)
p$etag <- gsub("mittwoch", "3", p$etag, fixed = TRUE)
p$etag <- gsub("donnerstag", "4", p$etag, fixed = TRUE)
p$etag <- gsub("freitag", "5", p$etag, fixed = TRUE)
p$etag <- gsub("samstag", "6", p$etag, fixed = TRUE)
p$etag <- gsub("sonntag", "7", p$etag, fixed = TRUE)

# Form der Protest (active 1, non active 2, crimes 3)
p$form <- gsub("1", "2", p$form, fixed = TRUE)
p$form <- gsub("3", "2", p$form, fixed = TRUE)
p$form <- gsub("8", "2", p$form, fixed = TRUE)
p$form <- gsub("10", "2", p$form, fixed = TRUE)
p$form <- gsub("11", "2", p$form, fixed = TRUE)
p$form <- gsub("12", "2", p$form, fixed = TRUE)
p$form <- gsub("22", "2", p$form, fixed = TRUE)

p$form <- gsub("4", "1", p$form, fixed = TRUE)
p$form <- gsub("5", "1", p$form, fixed = TRUE)
p$form <- gsub("6", "1", p$form, fixed = TRUE)
p$form <- gsub("12", "1", p$form, fixed = TRUE)
p$form <- gsub("13", "1", p$form, fixed = TRUE)
p$form <- gsub("14", "1", p$form, fixed = TRUE)
p$form <- gsub("15", "1", p$form, fixed = TRUE)
p$form <- gsub("7", "1", p$form, fixed = TRUE)
p$form <- gsub("98", "1", p$form, fixed = TRUE)

p$form <- gsub("16", "3", p$form, fixed = TRUE)
p$form <- gsub("17", "3", p$form, fixed = TRUE)
p$form <- gsub("18", "3", p$form, fixed = TRUE)
p$form <- gsub("19", "3", p$form, fixed = TRUE)
p$form <- gsub("20", "3", p$form, fixed = TRUE)
p$form <- gsub("21", "3", p$form, fixed = TRUE)
p$form <- gsub("29", "3", p$form, fixed = TRUE)

p
```

```{r var aufbereitung - Area, echo=FALSE}
p %>% 
  rename(
    i_zahl = zahl,
    x_verletzt = verletzt,
    x_etag = etag,
    x_artzahl = artzahl,
    x_festnahm = festnahm,
    x_schaden=schaden,
    x_form = form,
    z_ort = ort1
    )

p <-  arrange(p, i_codeverb, date)
p
```

```{r  , echo=FALSE}
 
p <-  arrange(p, i_codeverb, date)
write_xlsx(p,"/Users/sophiehensgen/Webscraping-LS-Methode/Protets/prodat-ready-for-edit.xlsx")

p <-  arrange(p, i_codeini, date)
write_xlsx(p,"/Users/sophiehensgen/Webscraping-LS-Methode/Protets/prodat-ready-for-edit-2.xlsx")

  

```


```{r kick out every observation that did not appear at least twice in our data set, echo=FALSE}
## nicht wichtig

p <-  arrange(p, i_codeverb, date)

p[p$i_codeverb %in% names(which(table(p$i_codeverb) == 1)), ]
p[p$i_codeverb %in% names(which(table(p$i_codeverb) >1)), ]

p <-  arrange(p, i_codeini, date)

p[p$i_codeini %in% names(which(table(p$i_codeini) > 1)), ]

```
##################################################################################
##################################################################################
##################################################################################

```{r load data set, echo=FALSE}

pverb <- read_excel("prodat-verband-full.xlsx")
pverb

pini <- read_excel("prodat-initiative-full.xlsx")
pini

pverbc <- read_excel("prodat-verband-full-change.xlsx")
pverbc

```


##################################################################################
##################################################################################
##################################################################################

```{r subset & description , echo=FALSE}

q <- subset(pverbc, diff >= 1)

# Bewertung Interest group & politisch administrative Seite

lapply(q[, c("diff", "i_bewertint", "i_bewertpol", "schaden", "verletzt", "form", "etag")], table)

```
```{r destription, echo=FALSE}

#subset prior so you don't have any nas in it
c <- q %>% 
  dplyr::select(diff, i_bewertint, schaden, verletzt, festnahm, form, etag, stand)%>%
  na.omit(schaden, verletzt)

e <- q %>% 
  dplyr::select(diff, i_bewertpol, schaden, verletzt, festnahm, form, etag, stand)%>%
  na.omit(i_berwertpol, schaden, verletzt, festnahm, form, etag)

```


```{r x tabs of main iv, echo=FALSE}

ftable(xtabs(~ diff + i_bewertint, data = c)) # kicking out c_no change as it has only two observations
ftable(xtabs(~ diff + i_bewertpol, data = e))

#ftable(xtabs(~ diff + i_bewertint, data = w)) --> not going to use the data set pini as it has not enough observations
#ftable(xtabs(~ diff + i_bewertpol, data = w))
```

```{r summary of iv, echo=FALSE}

summary(c$i_bewertint)
summary(e$i_bewertpol)

#summary(w$i_bewertint)
#summary(w$i_bewertpol)
```

```{r standard deviation, echo=FALSE}
sd(c$i_bewertint)
sd(e$i_bewertpol)

#sd(w$i_bewertint)
#sd(w$i_bewertpol)
```


```{r description, echo=FALSE}

ggplot(c, aes(x = diff, y = i_bewertint, group = schaden)) +
  geom_boxplot(size = .75) +
  geom_jitter(alpha = .5) +
  facet_grid(schaden ~ verletzt, margins = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))


ggplot(e, aes(x = diff, y = i_bewertpol, group = schaden)) +
  geom_boxplot(size = .75) +
  geom_jitter(alpha = .5) +
  facet_grid(schaden ~ verletzt, margins = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

##################################################################################
##################################################################################
##################################################################################


```{r ordered logistic regression - pverbc, echo=FALSE}
#### regression for pverbc
c$diff <- as.factor(c$diff)
e$diff <- as.factor(e$diff)


## Evaluation interest group
## fit ordered logit model and store results 'm'
m <- polr(diff ~ i_bewertint, data = c, Hess=TRUE)
mp <- polr(diff ~ i_bewertint, data = c, Hess=TRUE, method = "probit")


## predicted probabilities
m.pred <- predict(mm, type="probs")
summary(m.pred)

setup1 <- data.frame(verletzt = rep(mean(c$verletzt),3),
                     schaden = rep(mean(c$schaden),3),
                     festnahm = rep(mean(c$festnahm),3),
                     stand= rep(mean(c$stand),3),
                     i_bewertint=c(0,1,2))
setup1

setupprob <- predict(mm, newdata=setup1, type="probs") 

setup <- cbind(setup1, setupprob)
setup

## fit ordered logit model and store results 'mm' plus control variables
mm <- polr(diff ~ i_bewertint + verletzt + schaden + festnahm + stand, data = c, Hess=TRUE)

## view a summary of the model
summary(m)
summary(mm)

## evaluation political side

## fit ordered logit model and store results 'n'
n <- polr(diff ~ i_bewertpol, data = e, Hess=TRUE, method = "logistic")

## fit ordered logit model and store results 'nn'
nn <- polr(diff ~ i_bewertpol + verletzt + schaden + festnahm + etag + stand, data = e, Hess=TRUE)

## view a summary of the model
summary(n)
summary(nn)

```

```{r p value - pverbc & i_bewertini, echo=FALSE}
# simple regression
## store table
cmtable <- coef(summary(m))

## calculate and store p values
pvm <- pnorm(abs(cmtable[, "t value"]), lower.tail = FALSE) * 2

## combined table
cmtable <- cbind(cmtable, "p value" = pvm)
cmtable

##############################################################
# multiple regression
## store table
cmmtable <- coef(summary(mm))

## calculate and store p values
pvmm <- pnorm(abs(cmmtable[, "t value"]), lower.tail = FALSE) * 2

## combined table
cmmtable <- cbind(cmmtable, "p value" = pvmm)
cmmtable

```

```{r p value - pverbc & i_bewertpol, echo=FALSE}

# simple regression
## store table
cntable <- coef(summary(n))

## calculate and store p values
pvn <- pnorm(abs(cntable[, "t value"]), lower.tail = FALSE) * 2

## combined table
cntable <- cbind(cntable, "p value" = pvn)
cntable

##############################################################

# multiple regression
## store table
cnntable <- coef(summary(nn))

## calculate and store p values
pvnn <- pnorm(abs(cnntable[, "t value"]), lower.tail = FALSE) * 2

## combined table
cnntable <- cbind(cnntable, "p value" = pvnn)
cnntable
```



```{r confidence interval & OR - pverbc, echo=FALSE}
## Evaluation by interest group

cim <- confint(m)
cim

## odds ratios
exp(coef(m))

## OR and CI
exp(cbind(OR = coef(m), cim))

##############################################################

cimm <- confint(mm)
cimm

## odds ratios
exp(coef(mm))

## OR and CI
exp(cbind(OR = coef(mm), cimm))
```

```{r confidence interval & OR - pverbc, echo=FALSE}
## Evaluation by political side

cin <- confint(n)
cin

## odds ratios
exp(coef(n))

## OR and CI
exp(cbind(OR = coef(n), cin))

##############################################################

cinn <- confint(nn)
cinn

## odds ratios
exp(coef(nn))

## OR and CI
exp(cbind(OR = coef(nn), cinn))
```
























































